name: Schedule Next Newspaper Download Attempt (With Retries)

on:
  workflow_dispatch:
    inputs:
      retry_attempt:
        description: 'Next retry attempt number (2 or 3)'
        required: true
      date:
        description: 'Date folder for the newspapers (dd-mm-yyyy)'
        required: true

jobs:
  schedule-next-attempt:
    runs-on: ubuntu-latest
    permissions:
      actions: write  # Required to trigger other workflows
    
    steps:
      - name: Wait for 1 hour
        run: |
          echo "Waiting 1 hour before attempting retry #${{ github.event.inputs.retry_attempt }} for date ${{ github.event.inputs.date }}..."
          echo "Started waiting at: $(date)"
          sleep 3600  # Wait for 1 hour (3600 seconds)
          echo "Finished waiting at: $(date)"
      
      - name: Trigger next download attempt
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(`Triggering attempt #${{ github.event.inputs.retry_attempt }} for newspapers...`);
            
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'schedule_with_retries.yml',
              ref: context.ref,
              inputs: {
                retry_attempt: '${{ github.event.inputs.retry_attempt }}',
              }
            });
            
            console.log('Next attempt workflow triggered successfully');