name: Telegram Media Downloader

on:
  schedule:
    - cron: '30 5 * * *'  # Runs daily at 5:30 AM UTC
  workflow_dispatch:

jobs:
  telegram_downloader:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt

    - name: Set up Folder Structure
      run: |
        mkdir -p $(date +%d-%m-%Y)

    - name: Set date environment variable
      id: vars
      run: echo "date_dir=$(date +'%d-%m-%Y')" >> $GITHUB_OUTPUT

    - name: Download Telegram Media
      env:
        TELEGRAM_SESSION_STRING: ${{ secrets.TELEGRAM_SESSION_STRING }}
      run: |
        source .venv/bin/activate
        python telegram_downloader.py
        echo "::notice::Telegram media download completed."

    # - name: Save Artifacts
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: ${{ steps.vars.outputs.date_dir }}
    #     path: ${{ github.workspace }}/${{ steps.vars.outputs.date_dir }}/

    - name: Send Emails (Separate for Each Newspaper)
      env:
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        ADDITIONAL_EMAIL_RECEIVERS: ${{ secrets.ADDITIONAL_EMAIL_RECEIVERS }}
      run: |
        source .venv/bin/activate
        echo "::notice::Starting email delivery process with separate emails for each newspaper..."
        pip install pytz
        python send_email.py
        echo "::notice::Email delivery process completed - Indian Express and The Hindu sent separately"
        
    - name: Upload Files to Google Drive
      if: always()
      env:
        GOOGLE_DRIVE_CREDENTIALS: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
        GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
      run: |
        source .venv/bin/activate
        echo "::notice::Starting Google Drive upload process..."
        python drive_uploader.py
        echo "::notice::Google Drive upload process completed"
